### PR TITLE
check if streams2 is readable

### PR DESCRIPTION
**Pull request by jonathanong**
if the `end` event is emitted between `yield`s, it'll hang. i was going to add a test for this, but i can't seem to figure out how tap works. haha

### CODE REVIEW

**Comment by juliangruber** [comment]
thanks!

I added a test too: https://github.com/juliangruber/co-read/commit/e732ff704c1b8a427341abbf568c8ec15a958781

Tap isn't really that much different from mocha, instead of

``` js
describe('foo', function() {
  it('should bar', function() {
    assert(true);
  })
  it('should baz', function(done) {
    doSomeThings(done);
  })
})
```

You have

``` js
test('foo', function(t) {
  test('bar', function(t) {
    t.assert(true)
    t.end()
  })
  test('baz', function(t) {
    t.plan(1)
    doSomeThings(t.error.bind(t))
  })
})
```

**Comment by juliangruber** [comment]
released as `0.0.1`

**Comment by jonathanong** [comment]
Oh it was the plan thing. I have no idea what that is. I'll look into tap later.

**Comment by juliangruber** [comment]
`t.plan(3)` tells tap that the test is done after 3 assertion methods have been called. that makes especially eventemitter based tests easier to write.

**Pull request merged**
