### PR TITLE
clean up read1 streams

### PR DESCRIPTION
**Pull request by matthewmueller**
Hey so I wanted to take a stab at cleaning up the streams1 implementation. The tests are passing just fine including the backpressure one.

Haven't worked with streams too much so I definitely could be missing something. Two open questions about streams1 right off the top:

1) should we be pausing immediately?
2) does `stream.on('end', fn)` ever have data passed through it

Overall I think this change will make read streams with generators easier to understand. The yield within a yield was a big of a mindfuck for me at least, haha. But after playing around with the example, it actually didn't seem necessary.

### CODE REVIEW

**Comment by juliangruber** [comment]
i wonder what travis is up to, it doesn't get this PR https://travis-ci.org/juliangruber/co-read/pull_requests

**Comment by juliangruber** [comment]
looks good :)

**Comment by matthewmueller** [comment]
oh that is weird, it's not showing up in the UI either.

**Comment by matthewmueller** [comment]
sweeet

**Pull request merged**
